"""Offline gates for the local main-only runner; no providers or process launches."""
import copy
import hashlib
import json
import os
import tempfile
from pathlib import Path
import re
from urllib.parse import urlparse, unquote


def load(path):
    return json.loads(Path(path).read_text())


def bind(path):
    path = Path(path).resolve(strict=True)
    data = path.read_bytes()
    return {'path': str(path), 'sha256': hashlib.sha256(data).hexdigest(), 'bytes': len(data)}


def verified(ref):
    if not isinstance(ref, dict) or bind(ref['path']) != ref:
        raise ValueError('Changed or malformed evidence binding')
    return Path(ref['path'])


def write_once(path, value):
    """Atomically publish immutable JSON; readers never see a partially written gate."""
    path = Path(path)
    data = (json.dumps(value, indent=2, ensure_ascii=False) + '\n').encode()
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        if path.read_bytes() != data:
            raise ValueError('Preserve prior artifact; choose a new run: ' + str(path))
        return path
    with tempfile.NamedTemporaryFile(dir=path.parent, prefix='.'+path.name, delete=False) as stream:
        temporary = Path(stream.name)
        stream.write(data);stream.flush();os.fsync(stream.fileno())
    try:
        try:
            os.link(temporary, path)
        except FileExistsError:
            if path.read_bytes() != data:
                raise ValueError('Concurrent immutable artifact differs: ' + str(path))
    finally:
        temporary.unlink()
    return path


def refresh_manifest(full, generated, selected, inspect_sections):
    """Rebind every exact heading to actual generated bytes, never guessed offsets."""
    value = copy.deepcopy(full)
    spans = {row['heading']: row for row in inspect_sections(generated)}
    if set(spans) != {row['heading'] for row in value['entries']}:
        raise ValueError('Generated catalogue scope changed')
    if len(selected) != 4 or len(set(selected)) != 4 or set(selected) - {e['id'] for e in value['entries']}:
        raise ValueError('Exactly four preregistered refresh identities required')
    for entry in value['entries']:
        entry['span'] = {k: spans[entry['heading']][k] for k in ('start_byte', 'end_byte')}
    value.update(mode='refresh', selected_ids=selected)
    return value


def inspect_bundle(proposal_path, api_function_ids, cap=12000):
    """Schema/coverage checks only. A regex name match does not prove Scala semantics."""
    proposal = load(proposal_path)
    artifacts = proposal['artifacts']
    for ref in artifacts.values():
        verified({k: ref[k] for k in ('path', 'sha256', 'bytes')})
    if not {'readme', 'alias_interface', 'error_hints'} <= set(artifacts):
        raise ValueError('Complete README, alias interface and hint bundle required')
    interface = Path(artifacts['alias_interface']['path']).read_text()
    if not interface.strip() or len(interface) > cap:
        raise ValueError('Complete alias interface must fit the cap without clipping')
    sources = [ref for key, ref in artifacts.items() if key == 'alias' or re.fullmatch(r'alias_\d+', key)]
    if not sources:
        raise ValueError('No alias source')
    source_text = '\n'.join(Path(ref['path']).read_text() for ref in sources)
    reverse = {v: k for k, v in api_function_ids.items()}
    aliases, names = [], set()
    for row in proposal.get('aliases', []):
        name, target = row['name'], row['target_function']
        if target not in reverse or name in names or not re.fullmatch(r'[A-Za-z_]\w*', name):
            raise ValueError('Ambiguous or unknown alias metadata; requires review')
        if not re.search(r'\bdef\s+' + re.escape(name) + r'\s*(?:\[|\()', source_text):
            raise ValueError('Alias definition is not identifiable; requires review')
        names.add(name)
        aliases.append({'api': reverse[target], 'function_id': target, 'alias_name': name})
    if not aliases:
        raise ValueError('No supported aliases: five-condition execution requires review')
    covered = sorted({row['api'] for row in aliases})
    return {'status': 'structural_preflight_only', 'proposal': bind(proposal_path),
            'artifacts': artifacts, 'alias_interface_characters': len(interface),
            'alias_cap': cap, 'interface_full_fit': True, 'aliases': aliases,
            'alias_target_coverage': covered, 'untreated_targets': sorted(set(api_function_ids)-set(covered)),
            'behavior_validated': False, 'alias_jvm_mapping': 'requires_real_probe_and_review'}


def hint_delivery(bundle_check, diagnostics_path, mapping, documents, selection, public_context):
    """Exercise the exact public-context function using only development errors."""
    path = bundle_check['artifacts']['error_hints']['path']
    diagnostics = [json.loads(line) for line in Path(diagnostics_path).read_text().splitlines() if line.strip()]
    if len(diagnostics) != 4 or any(row.get('split') != 'development' for row in diagnostics):
        raise ValueError('Exactly four independent development diagnostics required')
    reverse = {v: k for k, v in mapping.items()}
    cfg = {'common': {'documentation_max_characters': 8000, 'documentation_selection': selection,
                     'alias_max_characters': 12000, 'hint_max_characters': 1500},
           'api_function_ids': mapping, 'conditions': {'error_hints_only': {'documents': documents, 'error_hints': path}}}
    frozen = {'config': cfg}
    rows = []
    for diagnostic in diagnostics:
        function = diagnostic.get('function', diagnostic.get('function_id'))
        if function not in reverse:
            raise ValueError('Development diagnostic identity missing from canonical map')
        api = reverse[function]
        case = {'prompt': 'Development-only delivery probe.', 'public_context': '', 'target_apis': [api]}
        previous = {'code': diagnostic['code'], 'feedback': diagnostic['error']}
        _, pos = public_context(frozen, 'error_hints_only', case, previous)
        _, initial = public_context(frozen, 'error_hints_only', case)
        _, negative = public_context(frozen, 'error_hints_only', case, {**previous, 'feedback': ''})
        foreign = copy.deepcopy(frozen)
        foreign['config']['api_function_ids'][api] = '__unrelated_development_function__'
        _, wrong = public_context(foreign, 'error_hints_only', case, previous)
        if initial['hints']['delivered'] or negative['hints']['delivered'] or wrong['hints']['delivered']:
            raise ValueError('Hint leaked into an initial/unmatched/wrong-function request')
        rows.append({'api': api, 'function_id': function, 'matched': pos['hints']['matched'],
                     'delivered': pos['hints']['delivered'], 'truncated': pos['hints'].get('truncated', False),
                     'characters': pos['hint_characters'], 'negative_checks_pass': True})
    return {'status': 'development_delivery_checked', 'diagnostics': bind(diagnostics_path),
            'hints': bind(path), 'diagnostic_count': 4,
            'positive_coverage': sum(bool(row['delivered']) for row in rows), 'rows': rows,
            'audience_error_coverage_proven': False, 'hint_content_correctness_proven': False}


def require_review(path, artifact_manifest, proposal_path=None):
    """Accept hash-bound root review or evidence-backed automatic source review."""
    value = load(path)
    if value.get('held_out_bank_used_for_development') is not False:
        raise ValueError('Development-only review is required')
    if value.get('status') == 'validated_proposal_sources' and proposal_path:
        proposal = load(proposal_path)
        actual = [ref for ref in proposal['source_proposals'] if Path(ref['path']).suffix == '.json']
        if value.get('proposal_bindings') != actual or not value.get('source_checks'):
            raise ValueError('Source review does not cover the exact complete proposal collection')
        for ref in [*actual, *value['source_checks']]:
            verified(ref)
        checks = [load(ref['path']) for ref in value['source_checks']]
        if len(checks) != len(actual):
            raise ValueError('Each actual proposal needs one strict source-check receipt')
        for proposal_ref, check in zip(actual, checks):
            certificates = check.get('certificates')
            if (check.get('status') != 'verified_forwarding_source' or check.get('proposal') != proposal_ref
                    or check.get('behavior_validated') is not False or check.get('hint_correctness_validated') is not False
                    or not isinstance(certificates, list) or len(certificates) != len(load(proposal_ref['path']).get('aliases', []))):
                raise ValueError('Source check is not a passing exact proposal validation')
            for certificate in certificates:
                if certificate.get('status') != 'supported_thin_forwarding_syntax':
                    raise ValueError('Unsupported alias source certificate')
                verified(certificate['source']);verified(certificate['canonical_source'])
        return {**value, 'final_artifact_manifest': bind(artifact_manifest)}
    if (value.get('status') not in ('approved_for_installation', 'validated_for_installation')
            or value.get('artifact_manifest') != bind(artifact_manifest)
            or not isinstance(value.get('reviewer'), str) or not value['reviewer'].strip()):
        raise ValueError('Exact artifact-bound installation review is required')
    return value


def _observations(run, expected_mode):
    process = load(verified(run['process']))
    if process.get('returncode') != 0:
        raise ValueError('Development JVM process did not succeed')
    stdout = verified(run['stdout']).read_text()
    for field in ('stderr', 'trace', 'classload'):
        verified(run[field])
    marked = [line.split('=', 1)[1] for line in stdout.splitlines() if line.startswith('AIDEAL_DEVELOPMENT_PROBE=')]
    if len(marked) != 1:
        raise ValueError('Expected exactly one raw development observation record')
    record = json.loads(marked[0])
    values = record.get('observations')
    if record.get('mode') != expected_mode or not isinstance(values, list) or not values or any(not isinstance(x, str) for x in values):
        raise ValueError('Invalid raw development observations')
    return values


def _loaded_from(log, owner, overlay):
    matches = []
    for line in log.splitlines():
        if '] ' in line and ' source: ' in line:
            name, source = line.split('] ')[-1].split(' source: ', 1)
            if name == owner:
                value = urlparse(source)
                matches.append(value.scheme == 'file' and Path(unquote(value.path)).resolve() == overlay)
    return bool(matches) and all(matches)


def require_alias_probes(path, bundle_check, backends_path, backend_receipts, target_events):
    """Recheck separately executed canonical/alias observations and alias-side trace."""
    value = load(path)
    if (value.get('status') != 'verified_alias_behavior'
            or value.get('proposal') != bundle_check['proposal']
            or value.get('backends') != bind(backends_path)
            or value.get('held_out_bank_used_for_development') is not False):
        raise ValueError('Independent development alias probes missing or stale')
    if load(verified(value['backend_receipts'])) != backend_receipts:
        raise ValueError('Probe backends differ from the configured condition receipts')
    verified(value['plan'])
    expected = {(arm, row['api'], row['alias_name']) for arm in ('alias_only', 'combined') for row in bundle_check['aliases']}
    seen = set()
    backends = load(backends_path)
    for row in value.get('probes', []):
        key = (row['arm'], row['api'], row['alias_name'])
        if key not in expected or key in seen:
            raise ValueError('Unexpected or duplicate alias probe')
        request = load(verified(row['request']))
        result = load(verified(row['process']))
        payload = result.get('payload', {})
        backend = backend_receipts[row['arm']]
        flags = ('execution_pass', 'paired_observations_pass', 'canonical_target_reached', 'alias_target_reached')
        if (result.get('status') != 'ok' or payload.get('backend_sha256') != backend['sha256']
                or request.get('backend') != backend or request.get('target_apis') != [row['api']]
                or request.get('protocol') != 'independent_development_alias_probe_v1'
                or request.get('plan') != value['plan'] or not all(payload.get(k) is True for k in flags)):
            raise ValueError('Alias probe failed actual execution/backend/target checks')
        for field in ('program', 'certificate', 'trace_policy'):
            verified(request[field])
        evidence = payload.get('adjudication_artifacts')
        if not isinstance(evidence, list) or not evidence:
            raise ValueError('Probe raw adjudication evidence missing')
        for ref in evidence:
            verified(ref)
        comparison = load(verified(row['comparison']))
        canonical = _observations(comparison['canonical_run'], 'canonical')
        alias = _observations(comparison['alias_run'], 'alias')
        if (canonical != alias or comparison.get('observations_equal') is not True
                or comparison.get('canonical_observations') != canonical or comparison.get('alias_observations') != alias):
            raise ValueError('Raw canonical and alias observations do not match')
        event = row['alias_event']; canonical_event = target_events[row['api']]
        if row.get('canonical_event') != canonical_event:
            raise ValueError('Wrong canonical JVM descriptor')
        alias_trace = verified(comparison['alias_run']['trace']).read_text().splitlines()
        canonical_trace = verified(comparison['canonical_run']['trace']).read_text().splitlines()
        if event not in alias_trace or canonical_event not in alias_trace or canonical_event not in canonical_trace:
            raise ValueError('Alias-side trace must contain both wrapper and exact target entries')
        owner, method = event.split('(', 1)[0].rsplit('.', 1)
        runtime = load(backends[row['arm']]['runtime'])
        build = load(verified(runtime['build_identity']))
        if (event not in payload.get('observed_alias_events', []) or '(' not in event
                or method != row['alias_name'] or owner not in build.get('alias_classes', [])
                or payload.get('build_sha256') != build['sha256'] or build['sha256'] != backends[row['arm']]['build_sha256']):
            raise ValueError('Actual alias JVM event does not match reviewed name/build')
        overlay = Path(verified(build['overlay'])).resolve()
        target_owner = canonical_event.split('(', 1)[0].rsplit('.', 1)[0]
        alias_log = verified(comparison['alias_run']['classload']).read_text()
        canonical_log = verified(comparison['canonical_run']['classload']).read_text()
        if not (_loaded_from(alias_log, owner, overlay) and _loaded_from(alias_log, target_owner, overlay)
                and _loaded_from(canonical_log, target_owner, overlay)):
            raise ValueError('Development targets did not load from their pinned overlay')
        seen.add(key)
    if seen != expected:
        raise ValueError('Not every proposed alias was behavior-probed in both alias arms')
    return {'status': 'verified_alias_behavior_evidence', 'receipt': bind(path), 'probe_count': len(seen),
            'method': 'separate JVM paired observations plus alias-side exact target/method trace'}
